# Generated by Django 3.1.4 on 2021-01-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topics',
            new_name='document',
        ),
    ]
