# Generated by Django 3.1.4 on 2021-02-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210216_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
