# Generated by Django 3.1.4 on 2021-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindocuments',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
