# Generated by Django 3.1.4 on 2021-02-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210217_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
        migrations.RenameModel(
            old_name='MainDocuments',
            new_name='MainDocument',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
