# Generated by Django 3.1.4 on 2021-04-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210411_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='data',
            new_name='date',
        ),
    ]
