# Generated by Django 3.1.4 on 2021-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210411_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('questoes', models.BigIntegerField()),
                ('valor', models.BigIntegerField()),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
    ]
